### ISSUE TITLE
Auth- error

### ISSUE THREAD

**Issue by atomoc** [julianlam/nodebb-plugin-sso-facebook#10]
After logging a red block error is output:
```
/forum/auth/facebook/callback
API calls from the server require an appsecret_proof argument
```
![2015-06-10 12 16 05](https://cloud.githubusercontent.com/assets/465108/8079008/80cf9e2e-0f6a-11e5-988f-e69ba3068ed4.png)

**Comment by julianlam** [comment]
Hi @atomoc, I am seeing no errors with the SSO plugin, so I cannot reproduce this issue...

**Comment by atomoc** [comment]
Sorry Jullian, I forgot to close the issue. With him everything is fine, except "#=_=", you probably know that.
