### ISSUE TITLE
Facebook Auth error:

### ISSUE THREAD

**Issue by tfraley** [julianlam/nodebb-plugin-sso-facebook#11]
Good day guys, 

Was wondering if one of you guys would be so kind to lend a hand. 

Can't seem to shake the "Given URL is not allowed...." error

My domain is                            lifewithtech.net    (Set in App domains)
My Forum is at      http://forum.lifewithtech.net:4567/ (Set in Site URL)

Valid OAuth redirect URIs  (i've tried many variations and no luck)
http://forum.lifewithtech.net:4567/auth/facebook 

I've been at this for about 2hrs and have hit a wall, I've tried as many variations as I can think of. Also starting and stoping the Facebook app between settings 

Any help would be greatly apreshiated. thanks

**Comment by julianlam** [comment]
Hi there, looks like [you're looked after here](https://community.nodebb.org/topic/6031/could-use-some-help-facebook-error) :smile:
