### ISSUE TITLE
Using with Reverse Proxy

### ISSUE THREAD

**Issue by KanwalPrakashSingh** [julianlam/nodebb-plugin-sso-facebook#12]
hey guys couldnt understand how to configure it for use with reverse proxy via nginx 

say nginx listens on 80 and node js runs on 8080 , I was unable to register or login via fb , because i had blocked 8080 access, is there a way, i can tell the plugin to not make request to 8080 but to 80?

**Comment by julianlam** [comment]
Yes, you'll need to update the `url` in `config.json` to point to the proper address that users will access your forum by.
