### ISSUE TITLE
Facebook Login / Registration Returns the wrong email 

### ISSUE THREAD

**Issue by KanwalPrakashSingh** [julianlam/nodebb-plugin-sso-facebook#13]
Hi Guys,
The FB login returns <user_id_fb>@facebook.com as email. 
Why is this happening? The app (facebook app) is having full permissions to access the email , then why does this wrong email id received

There seems to be a problem in passport-facebook, in response i view these two fields  {
  "name": "xcscsc",
  "id": "23232323232323"
}

**Comment by julianlam** [comment]
Hi @KanwalPrakashSingh, the idea is:

* If we receive the user email, then use that email as part of their NodeBB account
* If we do not have access to their email, create the generic facebook email, which is your fbid prepended to `@facebook.com`

I do not remember if we have access to the emails, but I'll look into it today...

**Comment by KanwalPrakashSingh** [comment]
But the permissions in my app created on FB, does have access to emails

**Comment by murphomatic** [comment]
I'm having the same issue - Facebook app lists email as an approved item, yet the sso plugin defaults to the generic <user id>@facebook.com email address.

**Comment by julianlam** [comment]
Hello @KanwalPrakashSingh @murphomatic -- apologies for my inattention.

During testing, I have discovered that we do pass in the `email` scope as part of the OAuth process. At this point, when a user authorizes through Facebook, they are presented with this dialog:

![selection_058](https://cloud.githubusercontent.com/assets/923011/9471268/896ae9b4-4b1d-11e5-8fb4-dab150e6d2b7.png)

If at this point they click "Edit the info you provide" and uncheck "email", then the NodeBB (and by extension, the plugin) will not have access to the email, and will fall back to fbid@facebook.com. If they leave it as is (checked), then the email goes through as expected and is saved appropriately with their user account.

Perhaps revoke authorization for NodeBB from your Facebook user settings, and attempt a reconnection again? At this point, I cannot reproduce the issue.

**Comment by murphomatic** [comment]
What’s odd is that I have the app set to ask permission for email, and I allow access to email when connecting (not unchecking anything) .. but still get the facebook.com email address –

[cid:image001.png@01D0DF1D.E55C6E30]

[cid:image002.png@01D0DF1D.E55C6E30]

**Comment by KanwalPrakashSingh** [comment]
@murphomatic @julianlam same is the case with me

**Comment by andrejjama** [comment]
Same here. E-mail in Facebook permission popup is checked etc., but nodeBB user profile email is fbid@facebook.com

**Comment by AndiKnight** [comment]
Same here.

**Comment by julianlam** [comment]
To help me debug, please add `console.log(profile);` **after** the highlighted line in `library.js`, restart NodeBB, and try to log in. Let me know what the server outputs in the log.

https://github.com/julianlam/nodebb-plugin-sso-facebook/blob/e042fac332908b136030cdd3063a221cdb960d36/library.js#L61

**Comment by luofan189** [comment]
The issue is that the API requires to explicitly to specify the profile fields you want to include in the response. I created a PR to fix this: https://github.com/julianlam/nodebb-plugin-sso-facebook/pull/22

Feel free to merge it if you think it is OK, @julianlam

**Comment by julianlam** [comment]
v1.1.4

**Comment by julianlam** [comment]
Thanks @luofan189! I'm sure many people were bothered by this :)

I suppose I was using an old version of the Facebook API...
