### ISSUE TITLE
Save button does not work

### ISSUE THREAD

**Issue by Holyphoenix** [julianlam/nodebb-plugin-sso-facebook#16]
I put in my application key, my secret, then hit the blue hovering save button but nothing happens.  When I leave the settings page and return the settings I input are gone.  

I am using NodeBB .8.1

**Comment by Fastidious** [comment]
It worked for me, just right now. Using default Persona theme.

**Comment by NormandoHall** [comment]
Hi @Holyphoenix 

No Sign Up nor Sign In facebook button

![image](https://cloud.githubusercontent.com/assets/2943127/9750764/b632661a-5672-11e5-800f-c73ed6a1dfae.png)

**Comment by Fastidious** [comment]
@NormandoHall and @Holyphoenix, I had them all working one night, and the next day they will no longer show (only GitHub remained). Definitely something going on with either the SSO plugins, or NodeBB.

**Comment by Holyphoenix** [comment]
It was not showing up for me, but I couldn't get the setting saved so I wouldn't have expected it to.  

@NormandoHall When you go to the social configuration for facebook, does it have your settings saved in the inputs?

**Comment by julianlam** [comment]
The latest SSO Facebook plugin only works for v0.8.1 (maybe v0.8.0), but in any case, nbbpm should be advising you to install a specific version ([v0.3.3, according to nbbpm](https://packages.nodebb.org/api/v1/suggest?version=0.7.3&package=nodebb-plugin-sso-facebook)) to maintain functionality.

**Comment by Fastidious** [comment]
@julianlam what are those google and Facebook SSO with "confirmed" in their names? I am not using those, but aren't they confusing to have? I know, not related to issue. 

I currently have all SSO showing (Google, Facebook, Twitter and GitHub). I will keep this thread posted on whether any of them disappear. Last time I have to restart Nodebb to see Facebook's.

**Comment by julianlam** [comment]
I thought it was uBlock making them disappear?

The confirmed variants are created by @drewdotpro to automatically confirm the user's email upon registering.

**Comment by Fastidious** [comment]
@julianlam uBlock caused them **all** to no show. After domain was whitelisted, Facebook refused to show (but the others did) until I finally restarted. I will keep an eye on that.

The versions I have (not confirmed) provide the option to do just that (for Google and Facebook).

**Comment by julianlam** [comment]
> The versions I have (not confirmed) provide the option to do just that (for Google and Facebook).

Yes, @drewdotpro was kind enough to submit pull requests to expose this functionality, so those `*-confirmed` variants are essentially outdated now.

**Comment by drewdotpro** [comment]
> Yes, @drewdotpro was kind enough to submit pull requests to expose this functionality, so those *-confirmed variants are essentially outdated now.

I'm drewdotpro and I approve this message.

**Comment by Fastidious** [comment]
@julianlam this morning the Facebook icon is gone. It simply disappeared. After a stop/start from the shell--not from the web console, that one will not make a difference--the icons shows back. Something is not right with the Facebook plugin, wish there will be logs to prove it though.

**Comment by julianlam** [comment]
This is a weird set of symptoms, because the SSO routes are defined once, on application start, and shouldn't be removed unless another plugin does so (and even then, I don't think that'd be easy)... 

Does your app stay running throughout the night, or does it crash?

**Comment by Fastidious** [comment]
@julianlam yes, running all the time, no crashes.

**Comment by NormandoHall** [comment]
It is very strange. Now update twitter and google+ to 1.0.0 and facebook sso run like a charm and shows the bullet. But when I inserte twitter credentis again in twitter sso backend, facebook bullet dissapear from login screen.

@Holyphoenix about your question, is yes and no. When I click saves button, never shows me the screen "Your settings are saved". But when I reload the broswer, the api key and secrete still there.

I think there is something with other plugins. Now I was disabled twitter SSO plugin, and facebook bullet is visible again.

**Comment by julianlam** [comment]
@NormandoHall try again with latest twitter SSO plugin?

**Comment by NormandoHall** [comment]
Yes @julianlam , all my tests are bases on latest versions of these plugins

![image](https://cloud.githubusercontent.com/assets/2943127/9817305/6b44e6de-5878-11e5-8d30-a3d4c1de8cca.png)

**Comment by julianlam** [comment]
The original issue itself is non-reproducible, in any case...

**Comment by julianlam** [comment]
Not sure whether there's some interop problem between the various SSO plugins, however, but that should be opened in a new issue when the problematic plugin is identified.

**Comment by NormandoHall** [comment]
It is very strange, now I disabled all plgins and re-enabled all, ./nodebb upgrade and run like a charm.

Thanks @julianlam

**Comment by MasinAD** [comment]
Related to the described problem might be this observation: When I activate sso-google besides sso-facebook, the source looks this way:
```
<ul class="alt-logins">
				<li class="facebook"><a rel="nofollow" target="_top" href="/auth/facebook"><i class="fa  fa-3x"></i></a></li>
				<li class="google"><a rel="nofollow" target="_top" href="/auth/google"><i class="fa fa-google-plus-square fa-3x"></i></a></li>
			</ul>
```

If I use the browser's developer's tools to insert fa-facebook-square, the login button for facebook is shown.

**Comment by julianlam** [comment]
Unrelated, @MasinAD, but resolved now.

**Comment by julianlam** [comment]
v1.1.1
