### ISSUE TITLE
Facebook login disappears on activation of sso-twitter

### ISSUE THREAD

**Issue by MasinAD** [julianlam/nodebb-plugin-sso-facebook#20]
Not a dealbreaker, because it reappears when reloading NodeBB from shell. Annoying nonetheless. :-)

Ideally, I'd never have to touch them again once they are working, but at the moment I'm configuring quite heavily. At least, FB and G+ login are working right now.

**Comment by julianlam** [comment]
This bug doesn't make any sense, in that I can't imaging how those two plugins would conflict with each other :laughing: 

So it breaks when you reload NodeBB, but works afterwards? How did you fix it temporarilty?

**Comment by agusputra** [comment]
I experience the same. 
It has nothing to do with twitter - sso.
Facebook login disapperars If I press reload button from admin page (It happens each time I press reload on admin page.). 
And show up again after press restart. Check this issue :  #21
