### ISSUE TITLE
How to configure Facebook Login ? It is not showing any button on the node bb forum 

### ISSUE THREAD

**Issue by ashutoshpw** [julianlam/nodebb-plugin-sso-facebook#23]
I have installed via Node Plugins panel and there its status is active, but the problem is i cant figure out how to configure it (App ID and App Secret ) and also it is not showing any facebook login button on the nodebb forum.

**Comment by bachvtuan** [comment]
I have the same situation, I installed the plugin and activate it in admin and restart nodebb but see nothing on login page.
Please guide me

**Comment by julianlam** [comment]
You need to enter your Facebook credentials into the settings page.
