### ISSUE TITLE
App not setup: The developers of this app have not set up this app properly for Facebook login

### ISSUE THREAD

**Issue by betzerra** [julianlam/nodebb-plugin-sso-facebook#3]
It seems that Facebook changed something internally. My facebook SSO stopped working:

https://community.nodebb.org/topic/2472/facebook-sso-app-not-setup-the-developers-of-this-app-have-not-set-up-this-app-properly-for-facebook-login

Any idea why?

**Comment by julianlam** [comment]
Most likely you'll need to enable these options:

![image](https://cloud.githubusercontent.com/assets/923011/8705830/2c6ae446-2afa-11e5-9c14-cb27e7678cd7.png)
