### ISSUE TITLE
missing option to disable sso registration

### ISSUE THREAD

**Issue by Pappmann** [julianlam/nodebb-plugin-sso-facebook#32]
missing option that only registered users can login via Facebook sso
reason: force users to register via local registration, sso bypass all forum resrictions, for example:
[missing welcome notification](https://github.com/NodeBB/NodeBB/issues/4014)
[no admin approval](https://github.com/NodeBB/NodeBB/issues/4021)
[bypass invite email restriction](https://github.com/NodeBB-Community/nodebb-plugin-user-invitations/issues/15)
and
[sso registered users can´t change password](https://github.com/NodeBB/NodeBB/issues/3993)

**Comment by julianlam** [comment]
v3.2.0
