### ISSUE TITLE
Suddenly stopped working, no longer shows on login page 

### ISSUE THREAD

**Issue by DaveArthur** [julianlam/nodebb-plugin-sso-facebook#33]
Maybe this was caused by upgrading to v0.9.3. but not noticed till now, as the facebook login hadn't expired.

**Comment by julianlam** [comment]
![selection_075](https://cloud.githubusercontent.com/assets/923011/12451472/a4d716d8-bf57-11e5-82be-ec4dfe9ad0b0.png)

Hi there, can't reproduce this issue. When configured and restarted, the SSO login option shows up.

**Comment by DaveArthur** [comment]
OK strange, I just tried deactivating and reactivating, also installing and reinstalling and still no joy. 
Not getting any configuration option in the drop down plugins menu? 
(I can't remember if there was before or not but I'm presuming it would need a fb app ID) 
![fbsso-nodebb-1](https://cloud.githubusercontent.com/assets/5874591/12463444/65550632-bfbb-11e5-8777-2eddbe744f13.PNG)
![fbsso-nodebb-2](https://cloud.githubusercontent.com/assets/5874591/12463451/6bb8bf14-bfbb-11e5-8487-574c917273fc.PNG)

The site can be found here https://www.dahippo.com/forum/login

Sound like I may have to dig a bit deeper!

**Comment by julianlam** [comment]
Can you report your nodebb hash?

**Comment by DaveArthur** [comment]
Not sure what you mean by nodebb hash?

**Comment by julianlam** [comment]
@DaveArthur Just wanted to see which commit you were on. Can you run `git rev-parse HEAD` in the command line, from the nodebb dir?

**Comment by DaveArthur** [comment]
ok 9043a40c358c19658b8468387a253bc01e599905

**Comment by pauljang9** [comment]
I had same problem with nodeBB 0.9.4 and a version of a installed nodebb-plugin-sso-facebook which was 2.0.0 was quite suspicious while nodeBB showed that it's last version is 1.1.8 ( Unfortunately I miss a screen shot, but you may be able to check yours ).
Anyway I reinstalled a nodebb-plugin-sso-facebook with a explicit version 1.1.8, then BOOM! it works :)

Actually what I did is that

`npm install nodebb-plugin-sso-facebook@1.1.8`

**Comment by julianlam** [comment]
Yes, v2.0.0 is only cleared for NodeBB v1.0.0 :)
