### ISSUE TITLE
Welcome E-Mail sent to Facebook User Id

### ISSUE THREAD

**Issue by mementum** [julianlam/nodebb-plugin-sso-facebook#40]
A Welcome E-mail was sent to the `fbuid@facebook.com` e-mail address rather than to the e-mail that was properly fetched during registration over the Facebook SSO plugin.

The e-mail was duly rejected by Facebook with a `550` code error, indicating `INVALID_ADDRESS_ERROR`

**Comment by mementum** [comment]
The version is `3.0.4` (from `package.json`:  `"nodebb-plugin-sso-facebook@3.0.4",`

The real e-mail of the user is in the system and the e-mail was automatically validated. It's only that the welcome e-mail went out to this `fbuid@facebook.com` address.

**Comment by julianlam** [comment]
v3.0.6

**Comment by mementum** [comment]
Thx!
