### ISSUE TITLE
Patreon.com fork

### ISSUE THREAD

**Issue by gwhrengineering** [julianlam/nodebb-plugin-sso-facebook#42]
Hello, 

I am trying to create an sso plugin for Patreon.com.  I posted about this on the generic version of the plugin and you told me to fork google or facebook.  I have done so.  Now it connects to patreon but I am getting a url mismatch error.  Please see my fork for the code I am using:  https://github.com/gwhrengineering/nodebb-plugin-sso-facebook/blob/master/library.js

I am unsure how to proceed from here.  Any help would be greatly appreciated.  

Thanks

**Comment by dev2devportal** [comment]
Would really like to have a working patreon oauth for NodeBB!

**Comment by julianlam** [comment]
https://github.com/julianlam/nodebb-plugin-sso-patreon
