### ISSUE TITLE
Unlink Facebook account

### ISSUE THREAD

**Issue by estebanconstante** [julianlam/nodebb-plugin-sso-facebook#43]
I have an admin user. Then I created another user using my Facebook account.
However, when I associated my account with the admin user, I lost the access to the FB profile.

How can I unlink the Facebook account from the admin user?

**Comment by julianlam** [comment]
@estebanconstante The associations are kept in the hash `fbid:uid`. You'll just want to change the uid for your facebook account inside your database to point to the non-admin user again.

In redis, it's as simple as `redis-cli hset fbid:uid <your fbid> <your uid>`

Mongo is `db.objects.update({ _key: "fbid:uid" }, { $set: { "<your fbid>": "<your uid>" } });`

**Comment by julianlam** [comment]
Back up your db first, just in case 😄

**Comment by estebanconstante** [comment]
Awesome! And superb support wow.
