### ISSUE TITLE
Insecure Login Blocked

### ISSUE THREAD

**Issue by venil7** [julianlam/nodebb-plugin-sso-facebook#49]
created FB app, inserted app id and secret into NodeBB,

I get following message from FB:

```
Insecure Login Blocked: You can't get an access token or log in to this app from an insecure page. 
Try re-loading the page as https://
```

my NodeBB is served over HTTPS only

**Comment by julianlam** [comment]
What is the callback url you've specified?

**Comment by venil7** [comment]
@julianlam Unlike twitter plugin, this plugin did not suggest that I have to provide callback URL.
I can see however that facebook url takes following form:
`https://www.facebook.com/dialog/oauth?response_type=code&redirect_uri=http%3A%2F%2F127.0.0.1%3A4567%2Fauth%2Ffacebook%2Fcallback&scope=public_profile%2C%20email...`

suggesting that callback is 127.0.0.1 which is clearly wrong, how do I set redirect_uri though?

**Comment by julianlam** [comment]
The `redirect_uri` is passed by the plugin itself, and it takes its cues from your `config.json`. It looks like you'll want to change the `url` value in that file.
