### ISSUE TITLE
not working after nodebb updating to 1.17.X

### ISSUE THREAD

**Issue by ciaompe** [julianlam/nodebb-plugin-sso-facebook#56]
I updated nodebb 1.16.X to 1.17.X, after update if i enable sso-facebook nodebb not loading in the frontend also admin not works, check the attached screen shot of ./nodebb log[
![Screenshot 2021-05-29 at 01 14 59](https://user-images.githubusercontent.com/24355280/120049793-6c62db00-c01b-11eb-9c04-c80506153628.png)
](url)

**Comment by julianlam** [comment]
Hi, please use `sso-github` and not `sso-github2`, the latter is a working branch by @revir, also it does not seem related to sso-facebook, but that seems to be the source of your error.
